config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/landing_page'
  get 'simple_pages/bio'
  get 'simple_pages/portfolio'
  get 'simple_pages/contact'
  get 'simple_pages/index'

  root 'simple_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'simple_pages/thank_you'
  post 'payments/create'

  #Added 6.13
  mount ActionCable.server => '/cable'
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
    @products = Product.limit(3)
    @featured_product = Product.first
  end

  def landing_page
    @products = Product.limit(3)
    @featured_product = Product.first
  end

  def thank_you
    byebug
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]

    # Email Send
    UserMailer.contact_form(@email, @name, @message).deliver_now

    #ActionMailer::Base.mail(from: @email,
    #    to: 'qwerty.wla@gmail.com',
    #    subject: "A new contact form message from #{@name}",
    #    body: @message).deliver_now
  end
end

app/views/simple_pages/bio.html.erb
<section class="bio" id="bio">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-6">
        <br>
        <h4>About Me</h4>
        <p>Hello, I'm Wendy and I'm a game photographer. I explore virtual worlds and take pictures for a hobby. You can find my work under the portfolio section. If you would like to work together, please contact me.
        </p>
      </div>
      <div class="col-12 col-sm-6">
        <br>
        <h4>everything.qwertyful</h4>
        <p>What is qwertyful? The word is made up to express living in the world of technology. The word QWERTY is a keyboard layout which most people use. Go on and look at the first letter row of your keyboard. Isn't it cute?
      </div><!-- end col -->
    </div>
    <div class="row">
      <div class="col-12 col-sm-3">
      </div>
      <div class="col-12 col-sm-6">
        <br>
        <h4>Contact Information</h4>
          <p>
          <i class="fas fa-envelope"></i> qwerty.wla@gmail.com
          <br><i class="fas fa-phone"></i> (415) 347-1886
          </p>
      </div>
      <div class="col-12 col-sm-3">
      </div>
    </div>
  </div><!-- end container -->
</section><!-- end container -->

app/views/simple_pages/contact.html.erb
<section class="contact" id="contact">
  <div class="container">
    <div class="row">
      <div class="col-12 col-xs-12 col-sm-12 col-md-12">
	       <%= image_tag("contactlogo.jpg", style: "display: block; margin: auto;", class: "img-fluid") %>
      </div>
    </div>
    <div class="row">
      <div class="col-6 col-xs-6 col-sm-6 col-md-6">
        <br><br>
        <h4>Feedback</h4>
      	<p>Please feel free to get in touch with me. I would love to hear from you to discuss new projects, ideas, opportunities, or anything else creative! Inquries regarding commissions may take one to three business days for replies.
      	</p>
      	<h4><i class="fas fa-envelope"></i> Email</h4>
      	  <p>qwerty.wla@gmail.com</p>
      	<h4><i class="fas fa-phone"></i> Phone</h4>
      	  <p>(415) 347-1886
      	  <br>Monday – Friday 9:00am – 5:00pm PST
      	  </p>
      </div> <!-- end col -->
      <div class="col-6 col-xs-6 col-sm-6 col-md-6">
        <br><br>
        <%= flash[:notice] %>

        <%= form_with(url:"/simple_pages/thank_you", method: "post", local: true) do |form| %>

          <div class="row">
            <div class="col-md-6 form-group">
              <%= form.label :name %>
              <p><%= form.text_field :name, class: "form-control", placeholder: "Enter Name", required: true %></p>
            </div> <!-- end col -->
            <div class="col-md-6 form-group">
              <%= form.label :email %>
              <%= form.text_field :email, class: "form-control", placeholder: "Enter Email", required: true, validates: :email %>
            </div> <!-- end col -->
            <div class="col-md-12 form-group">
              <p><%= form.text_area :message, class: "form-control", placeholder: "Enter Your Message Here", rows: 5, required: true %></p>
            </div> <!-- end col -->
          </div> <!-- end form-row -->
          <%= form.submit 'Send', class:'btn btn-dark' %>
          <% end %>
        </div> <!-- end contactcol2 -->
    </div>
  </div>
</section> <!-- end contact section -->

app/views/simple_pages/index.html.erb
<section class="content-home">
  <div class="jumbotron jumbotron-fluid" id="homehero">
    <div class="row">
      <div class="col-3 col-md-3 col-sm-3">
      </div>
      <div class="col-3 col-md-3 col-sm-3">
        <div class=carousel-landing-page">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <% @products.each_with_index do |product, index| %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="#{'active' if index == 0}">
              </li>
              <% end %>
            </ol>
          <div class="carousel-inner">
            <% @products.each do |product| %>
            <div class="carousel-item<%= " active" if product == @products.first %>">
            <%= image_tag(product.image_url, class: "img-fluid product-img") %>
            <div class="carousel-caption">
            <%= product.name %>
            </div>
            </div>
            <% end %>
          </div><!-- end carousel inner -->
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
          </div> <!-- end carousel-indicators -->
        </div> <!-- end carousel -->
      </div><!-- end col -->
      <div class="col-3 col-md-3 col-sm-3">
        <h1>everything.qwertyful</h1>
        <h6>The Art of Video Game Photography</h6>
        <hr>
        Check out my <%= link_to "portfolio", simple_pages_portfolio_path %> for <%= link_to 'products', products_url %> to print!
        <br><hr><p align="left">
        The photographs are all captured virtually in games. The captures are raw with no modification to emphasis the natural immersion of the game displaying portraits, landscapes, and environments.<br><br><i>Your photographer - Wendy</i></p>
      </div>
      <div class="col-3 col-md-3 col-sm-3">
      </div>
    </div><!-- end row -->
  </div> <!-- end home image -->
</section> <!-- end home content -->

app/views/simple_pages/landing_page.html.erb
<section class="lpp" id="lpp">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md 12 col-sm 12">
        <h3>Welcome to</h3>
          <h2>everything.qwertyful</h2>
      </div>
    <div class="row">
      <div class="col-2 col-md-2 col-sm-2">
      </div>
      <div class="col-4 col-md-4 col-sm-4">
        <br>
        <div class=carousel-landing-page">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <% @products.each_with_index do |product, index| %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="#{'active' if index == 0}">
              </li>
              <% end %>
            </ol>
          <div class="carousel-inner">
            <% @products.each do |product| %>
            <div class="carousel-item<%= " active" if product == @products.first %>">
            <%= image_tag(product.image_url, class: "img-fluid product-img") %>
            <div class="carousel-caption">
            <%= product.name %>
            </div>
            </div>
            <% end %>
          </div><!-- end carousel inner -->
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
          </div> <!-- end carousel-indicators -->
        </div> <!-- end carousel -->
      </div><!-- end col -->
      <div class="col-3 col-md-3 col-sm-3">
        <h1>everything.qwertyful</h1>
        <h6>The Art of Video Game Photography</h6>
        <hr>
        Check out my <%= link_to "portfolio", simple_pages_portfolio_path %> for <%= link_to 'products', products_url %> to print!
        <br><hr><p align="left">
        The photographs are all captured virtually in games. The captures are raw with no modification to emphasis the natural immersion of the game displaying portraits, landscapes, and environments.<br><br><i>Your photographer - Wendy</i></p>
      </div>
      <div class="col-2 col-md-2 col-sm-2">
      </div>
    </div>
    <div class="row">
    </div>
  </div>
</section>

app/views/simple_pages/portfolio.html.erb
<section class="portfolio" id="portfolio">
  <div class="container">
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d1.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d2.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d3.jpg", class: "img-fluid" %>
      </div>
    </div>
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d4.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d5.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d6.jpg", class: "img-fluid" %>
      </div>
    </div>
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d7.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "d8.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "i1.jpg", class: "img-fluid" %>
      </div>
    </div>
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "i2.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "saf.jpg", class: "img-fluid" %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= image_tag "bdo1.jpg", class: "img-fluid" %>
      </div>
    </div><!-- row -->
  </div><!-- end container -->
</section>

app/views/simple_pages/portfolio1.html.erb
<section class="portfolio" id="portfolio">
  <div class="container">
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d1.jpg', alt: 'image'), image_path('d1.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Anchor&apos;s Line, Moon'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d2.jpg', alt: 'image'), image_path('d2.jpg'), data: { lightbox: 'Destiny', title: 'Destiny Headlands Venus'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d3.jpg', alt: 'image'), image_path('d3.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Broken Satellite, Moon'} %>
      </div>
    </div>
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d4.jpg', alt: 'image'), image_path('d4.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Old Russia, Earth'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d5.jpg', alt: 'image'), image_path('d5.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Summoning Pits, Moon'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d6.jpg', alt: 'image'), image_path('d6.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Traveler&apos;s Walk, Tower'} %>
      </div>
    </div>
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d7.jpg', alt: 'image'), image_path('d7.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Hanger, Tower'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('d8.jpg', alt: 'image'), image_path('d8.jpg'), data: { lightbox: 'Journey', title: 'Journey'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('i1.jpg', alt: 'image'), image_path('i1.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Anchor of Light, Moon'} %>
      </div>
    </div>
    <div class="row" id="gallery">
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('i2.jpg', alt: 'image'), image_path('i2.jpg'), data: { lightbox: 'Destiny', title: 'Destiny - Tower Plaza, Tower'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('saf.jpg', alt: 'image'), image_path('saf.jpg'), data: { lightbox: 'SAF', title: 'Seasons After Fall'} %>
      </div>
      <div class="col-12 col-md-4 col-sm-4">
        <%= link_to image_tag('bdo1.jpg', alt: 'image'), image_path('bdo1.jpg'), data: { lightbox: 'BDO', title: 'Black Desert Online - Weita Island, Cron Islands'} %>
      </div>
    </div>
    </div><!-- end container -->

app/views/simple_pages/thank_you.html.erb
<section class="contact" id="contact">
  <div class="container">
    <div class="row">
      <div class="panel-body">
        <p>Thank you. We have received your message and will respond as soon as possible.</p>
        <%= link_to 'Back to homepage', simple_pages_index_path %>
      </div><!-- / panel-body -->
    </div>
  </div>
</section>