config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/landing_page'
  get 'simple_pages/bio'
  get 'simple_pages/portfolio'
  get 'simple_pages/contact'
  get 'simple_pages/index'

  root 'simple_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'simple_pages/thank_you'
  post 'payments/create'

  #Added 6.13
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="form-group actions">
    <%= form.submit 'Submit', class: "btn btn-dark" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<section class="userinfo" id="userinfo">
  <div class="card border-dark">
    <div class="card-header border-dark">
      Editing User Display Name
    </div>
        <div class="card-body bg-light">
          <%= render 'form', user: @user %>
        </div>
        <div class="card-footer border-dark">
          <%= link_to 'Show', @user, class:'btn btn-dark'  %>
          <%= link_to 'Back', user_path(params[:id]), class:'btn btn-dark'  %>
        </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="userinfo" id="userinfo">
  <p id="notice"><%= notice %></p>

  <div class="card border-dark">
    <div class="card-header border-dark">
      Master User List
    </div>
    <div class="card-header border-dark">
      <%= link_to 'Create New User', new_user_path, class:'btn btn-dark' %>
    </div>
    <% @users.each do |user| %>
      <div class="card-body bg-light">
          First Name: <%= user.first_name %>
          <br />
          Last Name: <%= user.last_name %>
      </div>
      <div class="card-footer border-dark">
        <%= link_to 'Show', user, class:'btn btn-dark' %>
        <%= link_to 'Edit', edit_user_path(user), class:'btn btn-dark' %>
        <%= link_to 'Destroy', user, class:'btn btn-dark', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>
  </div>
</section>

app/views/users/new.html.erb
<section class="userinfo" id="userinfo">
  <div class="card border-dark">
    <div class="card-header border-dark">
      New User
    </div>
      <div class="card-body bg-light">
        <%= render 'form', user: @user %>
      </div>
      <div class="card-footer border-dark">
        <%= link_to 'Back', simple_pages_index_path, class:'btn btn-dark'  %>
      </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="userinfo" id="userinfo">
  <p id="notice"><%= notice %></p>

    <div class="card border-dark">
      <div class="card-header border-dark">
        User Display Name
      </div>
        <div class="card-body bg-light">
          First name:
          <%= @user.first_name %>
          <br />
          Last name:
          <%= @user.last_name %>
        </div>
        <div class="card-footer border-dark">
          <%= link_to 'Edit', edit_user_path(@user), class:'btn btn-dark' %>
          <%= link_to 'Back', simple_pages_index_path, class:'btn btn-dark' %>
        </div>
    </div>
</section>