config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/landing_page'
  get 'simple_pages/bio'
  get 'simple_pages/portfolio'
  get 'simple_pages/contact'
  get 'simple_pages/index'

  root 'simple_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'simple_pages/thank_you'
  post 'payments/create'

  #Added 6.13
  mount ActionCable.server => '/cable'
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :orders
  has_many :comments

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true

  def self.search(search_term)
    if Rails.env.production?
      Product.where("name ilike ?", "%#{search_term}%")
    else
      Product.where("name LIKE ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

  def views
   $redis.get("product:#{id}")
  end

  def viewed
   $redis.incr("product:#{id}")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
      logger.debug "My search found #{@products.count} products"
      # return filtered list here
    else
      @products = Product.all
      logger.debug "My search found #{@products.count} products"
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product.viewed
    @comments = @product.comments.order("created_at DESC")
    @views = @product.views
    @comments = @product.comments.paginate(page: params[:page], per_page: 2).order("created_at DESC")
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    #@products = Product.all
    #redirect_to products_url, notice: 'You do not have sufficient permission to edit this page.'
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to '/simple_pages/index' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_carousel.html.erb
<section class="content-landing-page">
	<div class=carousel-landing-page">
		<div id="carousel-indicators" class="carousel slide" data-ride="carousel">
		  <ol class="carousel-indicators">
		  	<% @products.each_with_index do |index| %>
        <li data-target="#carousel-indicators"<%= " active" if @product == @products.first %>" slide_to: index>
        <% end %>
		  </ol>
		  <div class="carousel-inner">
		  	<% @products.each do |product| %>
		    <div class="carousel-item<%= " active" if product == @products.first %>">
		      <%= image_tag(product.image_url, class: "img-fluid product-img") %>
		      <div class="carousel-caption">
		        <%= product.name %>
		      </div>
		    </div>
		    <% end %>
		  </div>
      <a class="carousel-control-prev" href="#carousel-indicators" role="button" data-slide="prev">
  		  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  		  <span class="sr-only">Previous</span>
  		</a>
  		<a class="carousel-control-next" href="#carousel-indicators" role="button" data-slide="next">
  		  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  		  <span class="sr-only">Next</span>
  		</a>
  	</div> <!-- end carousel-indicators -->
  </div> <!-- end carousel -->
</section> <!-- end section landing page -->

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
  <%= render comment %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <section class="product" id="product">
    <div class="container">
      <div class="row"
      <div class="container-notices">
        <% if notice %>
          <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
        <% end %>

        <% if alert %>
          <p id="alert" class="alert alert-warning" role="alert"><%= alert %></p>
        <% end %>
      </div>
      <div class="row">
        <div class="col-4 col-md-4 col-sm-4">
          <div class="card bg-light mb-3" id="productsform">
            <%= image_tag(@product.image_url, class: "img-fluid") unless @product.image_url.nil? %>
          </div>
        </div>
        <div class="col-6 col-md-6 col-sm-6">
          <div class="card bg-light mb-3" id="productsform">
            <br />
            <div class="form-group">
              <%= form.label :name %>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :description %>
              <%= form.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :image_url %>
              <%= form.text_field :image_url, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :price %>
              <%= form.text_field :price, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :colour %>
              <%= form.text_field :colour, class: "form-control" %>
            </div>
              <%= form.submit 'Update Product', class:"btn btn-dark" %>
              <%= link_to 'Show', @product, class: "btn btn-dark" %>
              <%= link_to 'Back', products_path, class: "btn btn-dark" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote:true) do |f| %>
    <p>
      <div class="rating">Rating: </div>
    </p>
    <div class="form-group">
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body, required: true %>
    </div>
    <p>
      <%= f.submit "Submit", class:'btn btn-dark' %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-4 col-md-4 col-sm-4 justify-content-center">
  <div class="card bg-light mb-3" id="productsbody">
    <%= image_tag(product.image_url, class: "img-fluid") unless product.image_url.nil? %>
    <%= product.name %>
    <br>
    <% logger.debug "Product name is #{product.name}"%>
    <%= product.description %>
    <br>
    <%= product.price ? product.price : 0 %> USD
    <%= link_to 'Show', product, class: "btn btn-dark" %>
    <%= link_to 'Edit', edit_product_path(product), class: "btn btn-dark" %>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<section class="product" id="product">
  <div class="container">
    <div class="row">
      <div class="container-notices">
        <% if notice %>
          <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
          <% end %>
          <% if alert %>
          <p id="alert" class="alert alert-warning" role="alert"><%= alert %></p>
          <% end %>
      </div>
    </div>
    <div class="row">
      <% cache(cache_key_for_products) do %>
      <%= render @products %>
      <% end %>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class:'btn btn-dark' %>

app/views/products/show.html.erb
<section class="product" id="product">
  <div class="container">
    <div class="row" data-product-id="<%= @product.id %>">

      <div class="col-md-1">
      </div>
      <div class="col-md-4">
        <%= image_tag(@product.image_url, class: "img-fluid img-zoom", data_zoom_image: "@product.image_url") %>
        <br><br>
        Views: <%= @product.views %>
        <!-- Remove from page <%= link_to 'Add to Cart', '#', class: "btn btn-success btn-block" %> -->
        <p align="right"><%= link_to 'Back', products_path, class: "btn btn-dark" %></p>
      </div>
      <div class="col-md-6">
        <h3 class="card-title"><%= @product.name %></h3>
        <p class="card-text"><%= @product.description %></p>
        <li class="list-group-item">Price: USD <%= @product.price ? @product.price : 0 %></li>
        <p class="mt-2"><div class="rated" id="average-rating" data-score="<%= @product.average_rating %>">Average Rating: </div></p>
        <%= form_with(url: '/payments/create') do |form| %>
        <p><%= render partial: "shared/stripe_checkout_button" %></p>
        <% end %>
        <%= render 'new_comment' %>
        <div class="col-md-3 alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
        <%= render 'comments' %>
        <div class="pagination-content"><%= will_paginate @comments %></div>
      </div>
      <div class="col-md-1">
      </div>
    </div>
  </div>
</section>