config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/landing_page'
  get 'simple_pages/bio'
  get 'simple_pages/portfolio'
  get 'simple_pages/contact'
  get 'simple_pages/index'

  root 'simple_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'simple_pages/thank_you'
  post 'payments/create'

  #Added 6.13
  mount ActionCable.server => '/cable'
end

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>everything.qwertyful</title>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
     <%= javascript_include_tag 'jquery.elevatezoom.js' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>
    <!--navbar starts here-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" role="navigation" id="navbar-main">
    <%= link_to "everything.qwertyful", root_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> <!-- end button -->

    <nav class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Home", simple_pages_index_path, class: "nav-link" %>
           <span class="sr-only">(current)</span>
        </li>
        <li class="nav-item">
          <%= link_to "Portfolio", simple_pages_portfolio_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Orders", orders_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bio", simple_pages_bio_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Account", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        </li>
        <% end %>
        <li>
          <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
          <div class="form-group btn-group btn-group-sm">
            <%= form.text_field :q, id: 'q', value: params[:q], class: "searchformf" %>
            <%= form.submit 'Search', class: "searchformb btn btn-dark"%>
            <% end %>
          </div>
      </ul>
    </nav>
  </nav> <!-- end nav container -->

  <div class="container-notices">
    <%= render 'layouts/flash_messages' %>
  </div>

  <%= yield %>

  <footer class="footer">
    <div class="footer">
      <div class="row">
        <div class="col-12 col-sm-12">
          <!-- social media icons only no links -->
          <i class="fab fa-facebook"></i>
          <i class="fab fa-twitter-square"></i>
          <i class="fab fa-instagram"></i>
          <i class="fab fa-youtube"></i>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-sm-12">
          &copy; 2019 everything.qwertyful
        </div>
      </div>
    </div>
  </footer> <!-- end footer -->
</body>
  <%= javascript_include_tag 'jquery.raty.js' %>
</html>